#!/bin/sh
#
# Startup script for flowd
#
# $Id: flowd,v 1.0 2010/09/21 14:49:53 cweinhold Exp $
#
# chkconfig: 345 88 12
# description: flowd captures netflow data from routers and switches

# config file is /usr/local/etc/flowd.conf

# Source function library.
. /etc/rc.d/init.d/functions

if [ -x /bin/echo ]
then
    ECHO=echo
fi

# determine the flow-capture port

PORT=`expr \( match $0 '.*-\([0-9]*\)' \) \| 2055`

TARGET=/dev/shm/$PORT
CONFIGFILE="-f /usr/local/etc/flowd-$PORT.conf"
PIDFILE="/var/run/flowd-$PORT.pid"

# See how we were called.
case "$1" in
  start)
	mkdir -p $TARGET
	${ECHO} -n "Starting flowd: "
	daemon /usr/local/sbin/flowd $CONFIGFILE

	${ECHO}
	;;
  stop)
	PID=`cat $PIDFILE`

	${ECHO} -n "Stopping flowd: "
	kill -QUIT $PID
	${ECHO} "OK"
	;;
  status)
	${ECHO} "Checking on status of all flowd instances:"
	ps auxw | grep flowd | grep -v pts
	${ECHO}
	;;
  restart)
	$0 stop
	$0 start
	;;
  reload)
	PID=`cat $PIDFILE`
	${ECHO} -n "Reloading flowd: "
	kill -HUP $PID
	${ECHO} "OK"
	;;
  *)
	${ECHO} "Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac

exit 0
