#!/bin/sh
#
# Startup script for flow-capture
#
# $Id: flow-capture,v 1.3 2003/05/08 14:49:53 dklann Exp $
#
# chkconfig: 345 88 12
# description: flow-capture captures netflow data from routers and switches

# Source function library.
# . /etc/rc.d/init.d/functions

##
## Get the proper function library.
## Set aliases for functions and some return codes
##
if [ -f /lib/lsb/init-functions ]; then
  . /lib/lsb/init-functions
  alias DAEMON=start_daemon
  alias STATUS=DaemonStatus
elif [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
  alias DAEMON=daemon
  alias STATUS=status
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
  alias DAEMON=daemon 
  alias STATUS=status
else
  exit 0
fi

if [ -x /bin/echo ]
then
    ECHO=echo
fi

# determine the flow-capture port

PORT=`expr \( match $0 '.*-\([0-9]*\)' \) \| 2055`

SHUFFLE=
if [ -x /usr/local/netflow/bin/flow-shuffle-$PORT ] 
then
	SHUFFLE="-R /usr/local/netflow/bin/flow-shuffle-$PORT"
elif [ -x /usr/local/netflow/bin/flow-shuffle ]
then
	SHUFFLE="-R /usr/local/netflow/bin/flow-shuffle"
fi

TARGET=/dev/shm/$PORT

# See how we were called.
case "$1" in
  start)
	mkdir -p $TARGET
	${ECHO} -n "Starting flow-capture-$PORT: "
	${DAEMON} /usr/local/netflow/bin/flow-capture \
		-w $TARGET \
		$SHUFFLE \
		-p /var/run/flow-capture.pid \
		-n 288 \
		-S 15 \
		-N 0 \
		-V 5 \
		-z 0 \
		0/0/$PORT

# Below are descriptions of what each of the above flow-capture options do.
# for more info, see http://www.splintered.net/sw/flow-tools/docs/flow-capture.html
#
#	-w /var/log/webview/flows/capture 	# directory to save data
#	-E 10G 		# max GB used for flow data
#	-e 9000 	# max number of flow files (~1 month)
#	-n 288 		# how many files per day. 288 = every 5 minutes.
#	-S 15 		# how often to save exporter stats to /var/log/messages
#	-N 0 		# directory structure = flat
#	-V 5 		# netflow version to write
#	0/0/2055	# localip/remoteip/port (udp port 2055)

	${ECHO}
	;;
  stop)
	PID=`cat /var/run/flow-capture.pid.$PORT`

	${ECHO} -n "Stopping flow-capture-$PORT: "
	kill -QUIT $PID
	${ECHO} "OK"
	;;
  status)
	${ECHO} "Checking on status of all flow-cature instances:"
	ps auxw | grep flow-capture | grep -v pts
	${ECHO}
	;;
  restart)
	$0 stop
	$0 start
	;;
  reload)
	PID=`cat /var/run/flow-capture.pid.$PORT`
	${ECHO} -n "Reloading flow-capture-$PORT: "
	kill -HUP $PID
	${ECHO} "OK"
	;;
  *)
	${ECHO} "Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac

exit 0
