#!/usr/bin/perl

# moves files from point A to point B

use strict;

my $sDir = "/usr/local/localcap";	# source
my $tDir = "/opt/netflow/capture";	# destination ( nfs://opt/netflow/capture )
my $semaphore = "/var/run/flow-mover";

if (-f $semaphore) {		# exists
	my $age = -M $semaphore;

	if ($age < 0.0416) {		# exists and is less than 1-hour old
		exit 0;
	}
	else {
		open(IN, $semaphore); my $pid = <IN>; close(IN);
		my $count = kill(9, $pid);
		&logit("Old PID file found - kill(9, $pid)=$count");
	}
}
open(OUT, ">$semaphore"); print OUT $$; close(OUT);

open(IN, "find $sDir -name 'ft*' -printf '%P\n' |");
while ( <IN> ) {
	chomp;

	my $cmd = "mv $sDir/$_ $tDir/$_";
	&logit($cmd);
	my $results = `$cmd`;

	if ($?) {		# error
		&logit("result=$?");
		&logit($results);
	}
	else {
		&logit("OK (" . (-s "$tDir/$_") . " bytes)");
	}
}
close(IN);

unlink($semaphore);

exit 0;

sub logit
{
	open(LOG, ">>/var/log/flow-mover.log");

	foreach (@_) {
		foreach (split(/\n/)) {
			print LOG (scalar localtime()), " ", $_, "\n";
		}
	}

	close(LOG);
}

